
package com.fxl.publish.cxftest;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "CxftestServiceImplService", targetNamespace = "http://impl.service.fxl.com/", wsdlLocation = "http://192.168.1.235:8080/webServer/cxf/cxftest?wsdl")
public class CxftestServiceImplService
    extends Service
{

    private final static URL CXFTESTSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException CXFTESTSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName CXFTESTSERVICEIMPLSERVICE_QNAME = new QName("http://impl.service.fxl.com/", "CxftestServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://192.168.1.235:8080/webServer/cxf/cxftest?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        CXFTESTSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        CXFTESTSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public CxftestServiceImplService() {
        super(__getWsdlLocation(), CXFTESTSERVICEIMPLSERVICE_QNAME);
    }

    public CxftestServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), CXFTESTSERVICEIMPLSERVICE_QNAME, features);
    }

    public CxftestServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, CXFTESTSERVICEIMPLSERVICE_QNAME);
    }

    public CxftestServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, CXFTESTSERVICEIMPLSERVICE_QNAME, features);
    }

    public CxftestServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public CxftestServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns CxftestService
     */
    @WebEndpoint(name = "CxftestServiceImplPort")
    public CxftestService getCxftestServiceImplPort() {
        return super.getPort(new QName("http://impl.service.fxl.com/", "CxftestServiceImplPort"), CxftestService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns CxftestService
     */
    @WebEndpoint(name = "CxftestServiceImplPort")
    public CxftestService getCxftestServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://impl.service.fxl.com/", "CxftestServiceImplPort"), CxftestService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (CXFTESTSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw CXFTESTSERVICEIMPLSERVICE_EXCEPTION;
        }
        return CXFTESTSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
